version: '3.8'

services:
  flask-app:
    build: .
    container_name: flask-app
    ports:
      - '5000:5000'
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    volumes:
      - ./data:/app/data